specVersion: "0.0.1"
description: "This subquery indexes bond,reward and slash of each block, summarize total earning of an account"
repository: "https://github.com/subquery/subql-examples"

schema: "./schema.graphql"

network:
  endpoint: wss://polkadot.api.onfinality.io/public-ws
  dictionary: https://api.subquery.network/sq/subquery/dictionary-polkadot

dataSources:
  - name: runtime
    kind: substrate/Runtime
    startBlock: 1
    mapping:
      handlers:
        - handler: handleBond
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Bonded
        - handler: handleReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
        - handler: handleStakingReward
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Reward
        - handler: handleStakingSlash
          kind: substrate/EventHandler
          filter:
            module: staking
            method: Slash
